global:
  # How frequently to scrape targets by default.
  # Default 15s
  scrape_interval: 15s
  # How frequently to evaluate rules.
  # Default 15s
  evaluation_interval: 15s
  # How long until a scrape request times out.
  # Default to 10s.
  # Required because cp-demo is using cpu throttling, so let's leave enough time to fetch the metrics in particular for the first time as it needs to compile all rexps
  scrape_timeout: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-platys'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "prometheus-alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus-1:9090"]


  - job_name: "node-exporter"
    static_configs:
      - targets: ["prometheus-nodeexporter:9100"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'


  - job_name: "zookeeper"
    static_configs:
      - targets:
          - "zookeeper-1:1234"
          - "zookeeper-2:1234"
          - "zookeeper-3:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'


  - job_name: "kafka-broker"
    static_configs:
      - targets:
          - "kafka-1:1234"
          - "kafka-2:1234"
          - "kafka-3:1234"
          - "kafka-4:1234"
          - "kafka-5:1234"
          - "kafka-6:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  - job_name: 'kafka-controller'
    static_configs:
      - targets: ['kafka-1:1234', 'kafka-2:1234', 'kafka-3:1234', 'kafka-4:1234', 'kafka-5:1234', 'kafka-6:1234']
        labels:
          env: "dev"

  - job_name: "schema-registry"
    static_configs:
      - targets:
          - "schema-registry-1:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'


  - job_name: "kafka-connect"
    static_configs:
      - targets:
          - "kafka-connect-1:1234"
          - "kafka-connect-2:1234"
          - "kafka-connect-3:1234"
        labels:
          env: "dev"
          kafka_connect_cluster_id: "cluster1"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'


  - job_name: "ksqldb"
    static_configs:
      - targets:
          - "ksqldb-server-1:1234"
          - "ksqldb-server-2:1234"
          - "ksqldb-server-3:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'


  - job_name: "streams-demo"
    static_configs:
      - targets:
          - "streams-demo:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  - job_name: "rest-proxy"
    static_configs:
      - targets:
          - "kafka-rest-1:1234"
          - "kafka-rest-2:1234"
          - "kafka-rest-3:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  # No producer for the moment in cp-demo
  # - job_name: 'kafka-producer'
  #   static_configs:
  #     - targets:
  #         - 'kafka1:1235'
  #       labels:
  #         env: 'dev'
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: hostname
  #       regex: '([^:]+)(:[0-9]+)?'
  #       replacement: '${1}'

  # No consumer for the moment in cp-demo
  # - job_name: 'kafka-consumer'
  #   static_configs:
  #     - targets:
  #         - "kafka1:1236"
  #       labels:
  #         env: 'dev'
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: hostname
  #       regex: '([^:]+)(:[0-9]+)?'
  #       replacement: '${1}'

  - job_name: "kafka-lag-exporter"
    static_configs:
      - targets:
          - "kafka-lag-exporter:9999"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  - job_name: etcd
    static_configs:
      - targets: ["etcd-1:2381"]

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['prometheus-pushgateway:9091']

  - job_name: risingwave-compute-1
    static_configs:
      - targets: ["risingwave-compute-1:1222"]
      - targets: ["risingwave:1222"]

  - job_name: risingwave-meta-1
    static_configs:
      - targets: ["risingwave-meta-1:1250"]
      - targets: ["risingwave:1250"]

  - job_name: risingwave-compactor-1
    static_configs:
      - targets: ["risingwave-compactor-1:1260"]
      - targets: ["risingwave:1260"]

  - job_name: risingwave-frontend-1
    static_configs:
      - targets: ["risingwave-frontend-1:2222"]
      - targets: ["risingwave:2222"]

  - job_name: minio-1
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ["minio-1:9000"]

  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://redis-1:6379
        - redis://redis-2:6379
        - redis://redis-3:6379
        - redis://valkey-1:6379
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter:9121

  ## config for scraping the exporter itself
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
        - redis-exporter:9121

  - job_name: zipkin
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['zipkin:9411']      

  - job_name: 'opal-server'
    static_configs:
      - targets: ['opal-server:7002']
    metrics_path: '/metrics'

  - job_name: 'opal-client'
    static_configs:
      - targets: ['opal-client:7000']
    metrics_path: '/metrics'

  - job_name: lakeFS
    scrape_interval: 10s
    static_configs:
      - targets: ['lakefs:8000']
    metrics_path: /metrics

  - job_name: 'litellm'
    static_configs:
      - targets: ['litellm:4000'] 

  - job_name: trino
    basic_auth:
      username: trino-user
      password:
    static_configs:
      - targets:
        - trino-1:12345
        - trino-2:12345
        - trino-3:12345

  - job_name: 'trino-lb'
    static_configs:
      - targets: ['trino-lb:9090']

  - job_name: trino-gateway
    static_configs:
      - targets: ['trino-gateway:8080']

  - job_name: lakekeeper
    static_configs:
      - targets: ['lakekeeper:9000']

  - job_name: 'polaris'
    scrape_interval: 5s
    metrics_path: /q/metrics
    static_configs:
      - targets: ['polaris:8182']
        labels:
          service: polaris      

  - job_name: metabase
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['metabase:9191']

  - job_name: 'airflow-exporter'
    static_configs:
      - targets: ['airflow-statsd-exporter:9102']

  - job_name: "streampipes-backend"
    metrics_path: "/streampipes-backend/actuator/prometheus"
    static_configs:
      - targets: [ "streampipes-backend:8030" ]
    bearer_token: "" # Write the value of the token
    #bearer_token_file: ""

  - job_name: "extensions-all-iiot"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["extensions-all-jvm:7023"]      

  - job_name: "ehrbase"
    metrics_path: "ehrbase/management/prometheus"
    static_configs:
      - targets: ["ehrbase:28282"]      

  - job_name: 'nessie'
    scrape_interval: 5s
    metrics_path: /q/metrics
    static_configs:
      - targets: ['nessie:9000']
        labels:
          service: nessie      

  - job_name: 'gravitino'
    static_configs:
      - targets: ['gravitino:8090']
    metrics_path: '/prometheus/metrics'          

  - job_name: puppygraph
    metrics_path: /metrics
    static_configs:
      - targets: ["puppygraph:8081"]
    basic_auth:
      username: puppygraph
      password: abc123!    

  - job_name: "flink"
    static_configs:
      - targets:
          - "flink-jobmanager:9249"
          - "flink-taskmanager-1:9249"
          - "flink-taskmanager-2:9249"
        labels:
          env: "dev"
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'flink_jobmanager_Status_JVM_CPU_Time'
        target_label: __name__
        replacement: 'flink_jobmanager_Status_JVM_CPU_Time_total'
      - source_labels: [__name__]
        regex: 'flink_taskmanager_Status_JVM_CPU_Time'
        target_label: __name__
        replacement: 'flink_taskmanager_Status_JVM_CPU_Time_total'
    relabel_configs: 
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  - job_name: "neo4j"
    static_configs:
      - targets: ["neo4j-1:2004"]

  - job_name: postgresql
    static_configs:
      - targets: ['postgresql-exporter:9187']      

  - job_name: "xtdb"
    static_configs:
      - targets:
          - "xtdb:8080"       

  - job_name: "n8n"
    static_configs:
      - targets: ["n8n:5678"]

  - job_name: 'spark_master'
    metrics_path: '/metrics/master/prometheus'
    static_configs:
      - targets: ['spark-master:28304']

  - job_name: 'spark_driver'
    metrics_path: '/metrics/prometheus'
    static_configs:
      - targets: ['spark-master:4040', 'spark-master:4041', 'spark-master:4042', 'spark-master:4043', 'spark-master:4044']                     
  - job_name: 'spark_workers'
    metrics_path: '/metrics/prometheus'
    static_configs:
      - targets: ['spark-worker-1:28111', 'spark-worker-2:28112']

  - job_name: 'spark_executors'
    metrics_path: '/metrics/executors/prometheus'
    static_configs:
      - targets: ['spark-master:4040', 'spark-master:4041', 'spark-master:4042', 'spark-master:4043', 'spark-master:4044']       

  - job_name: elasticsearch
    metrics_path: /probe
    # Default parameters for all scrapes in this job.
    # Can be overridden by labels on a per-target basis.
    params:
      auth_module: [prod_key]
    static_configs:
      # This is a target group. All targets here will use the default 'prod_key' auth_module.
      - targets:
          - https://elasticsearch-1:9200
        labels:
          __param_auth_module: staging_basic
    relabel_configs:
      # The following relabeling rules are applied to every target.

      # 1. The special label __address__ (the target address) is saved as the 'target' URL parameter.
      - source_labels: [__address__]
        target_label: __param_target

      # 2. The 'target' parameter is used as the 'instance' label for the scraped metrics.
      - source_labels: [__param_target]
        target_label: instance

      # 3. The scrape address is rewritten to point to the exporter.
      - target_label: __address__
        replacement: elasticsearch-exporter:9114 # host:port of the single exporter                    