# Nimtable config file to be mounted into the Docker containers.
# See backend/config.yaml for more complete example
server:
  port: 8182
  host: 0.0.0.0
database:
  # You can also point to your own Postgres database, instead of using the one provided by docker-compose.
  url: jdbc:postgresql://postgresql:5432/postgres
  username: postgres
  password: abc123!