serverConfig:
  node.environment: test
  http-server.http.port: 8080

routingRules:
  rulesEngineEnabled: ${ENV:RULES_ENGINE_ENABLED:-false}
  rulesType: ${ENV:RULES_TYPE:-FILE}
  rulesConfigPath: ${ENV:RULES_CONFIG_PATH:-'src/main/resources/rules/routing_rules.yml'}
  # rulesExternalConfiguration:
  #   urlPath: ${ENV:RULES_URL_PATH}
  #   excludeHeaders:
  #     - 'Authorization'
  #     - 'Accept-Encoding'

dataStore:
  jdbcUrl: jdbc:postgresql://${ENV:POSTGRES_HOST:-postgres}:5432/${ENV:POSTGRES_DB:-postgres}
  user: ${ENV:POSTGRES_USER:-postgres}
  password: ${ENV:POSTGRES_PASSWORD:-abc123!}
  driver: org.postgresql.Driver
  queryHistoryHoursRetention: 24

clusterStatsConfiguration:
  monitorType: INFO_API
