serverConfig:
  node.environment: test
  http-server.http.port: 8080
  log.levels-file: ${ENV:LOG_LEVELS_FILE:-'src/main/resources/log4j2.xml'}
  http-server.process-forwarded: true

routingRules:
  rulesEngineEnabled: ${ENV:RULES_ENGINE_ENABLED:-false}
  rulesType: ${ENV:RULES_TYPE:-FILE}
  rulesConfigPath: ${ENV:RULES_CONFIG_PATH:-'src/main/resources/rules/routing_rules.yml'}
  rulesExternalConfiguration:
    urlPath: ${ENV:RULES_URL_PATH:-'http://localhost:8080/rules'}
    excludeHeaders:
      - 'Authorization'
      - 'Accept-Encoding'

dataStore:
  jdbcUrl: jdbc:postgresql://${ENV:POSTGRES_HOST:-postgres}:5432/${ENV:POSTGRES_DB:-postgres}
  user: ${ENV:POSTGRES_USER:-postgres}
  password: ${ENV:POSTGRES_PASSWORD:-abc123!}
  driver: org.postgresql.Driver
  queryHistoryHoursRetention: 24
  runMigrationsEnabled: true

clusterStatsConfiguration:
  monitorType: INFO_API

# This can be adjusted based on the coordinator state
monitor:
  taskDelaySeconds: 10

routing:
  addXForwardedHeaders: false  

proxyResponseConfiguration:
  responseSize: 32MB  