---

#include_vars:
#  - vars-global.yml
vars:
  admin_password: abc123!
  restart: always
  docker_compose_version: 3.0
  container_restart_policy: unless-stopped

  PROVISIONING_DATA_version: latest

  #kafka related vars

  CONFLUENT_PLATFORM_version: 7.9.1
  KAFKA_version: 4.0.0
  KAFKA_INIT_version: latest
  KAFKA_MM2_version: 2.8.1
  APICURIO_SCHEMA_REGISTRY_version: 2.6.11.Final
  ZOONAVIGATOR_version: latest
  ZOONAVIGATOR_API_version: latest
  KSQLDB_version: 0.29.0
  MATERIALIZE_version: v0.146.1
  
  #HStreamDB
  HSTREAMDB_version: latest

  #Benthos
  BENTHOS_version: 4

  #Risingwave
  RISINGWAVE_version: v2.4.1

  #Timeplus Proton
  TIMEPLUS_ENTERPRISE_version: 2.8.1
  TIMEPLUS_PROTON_version: 1.6.16-rc

  #Arroyo
  ARROYO_version: 0.14.0

  #SQLFlow
  SQLFLOW_version: 0.6.0

  LENSES_BOX_version: latest
  KCAT_version: 1.7.1
  KASKADE_version: latest
  KAFKACTL_version: latest
  # using main version of Jikkou image, otherwise it doesn't work on Mac M1
  JIKKOU_version: main
  JIKKOU_SERVER_version: latest
  SCHEMA_REGISTRY_UI_version: latest
  KAFKA_TOPICS_UI_version: latest
  KAFKA_CONNECT_UI_version: latest
  CMAK_version: latest
  KAFDROP_version: latest
  KADMIN_version: latest
  AKHQ_version: latest
  KAFKA_UI_version: latest
  EFAK_version: latest
  KOWL_version: master
  REDPANDA_CONSOLE_version: latest
  KOUNCIL_version: latest
  KAFKA_MAGIC_version: latest
  KAFKA_WEBVIEW_version: latest
  KPOW_version: latest
  CONDUKTOR_PLATFORM_version: latest
  KADECK_version: latest
  KAFKISTRY_version: latest
  KLAW_version: nightly
  KAFKA_CONNECTOR_BOARD_version: latest
  ZILLA_version: latest

  STREAMS_EXPLORER_version: latest
  KAFKA_LAG_EXPORTER_version: latest
  
  REMORA_version: latest

  #Burrow
  BURROW_version: v1.9.4
  BURROW_UI_version: 1.1.0
  BURROW_DASHBOARD_version: 1.0.4
  
  DEBEZIUM_SERVER_version: 3.0.0.Final
  DEBEZIUM_UI_version: latest

  #hadoop related vars (if you change hadoop version, make sure to do it in both properties!!)
  HADOOP_image_version: 2.0.0-hadoop3.2.1-java8
  HADOOP_version : 3.2.1

  #spark
  SPARK_3_3_version: 3.3.4
  SPARK_3_4_version: 3.4.3
  SPARK_3_5_version: 3.5.3

  #Kyuubi
  KYUUBI_version: 1.10.0-all

  #flink
  FLINK_version: 2.0.0-scala_2.12-java17

  # Nussknacker
  NUSSKNACKER_version: staging-latest

  # Apache Avro Tools
  AVRO_TOOLS: latest

  # Apache Parquet Tools
  PARQUET_TOOLS: master

  # OpenLDAP
  OPENLDAP_version: 1.5.0

  # phpLDAPadmin
  PHP_LDAP_ADMIN_version: latest

  # LDAP user manager
  LDAP_USER_MANAGER_version: latest
  
  # apache livy
  LIVY_version: 0.7.1-incubating

  #tika
  TIKA_version: 3.2.0.0-full

  #tika
  NLM_INGESTOR_version: latest

  #Unstructured.IO
  UNSTRUCTURED_version: latest
  
  #SearXNG
  SEARXNG_version: latest

  #Firecrawl
  FIRECRAWL_version: latest

  #Crawl4ai
  CRAWL4AI_version: latest

  #MCP Toolbox for Databases
  MCP_TOOLBOX_version: latest 

  #CentralMind Gateway
  CENTRALMIND_GATEWAY_version: latest

  #MCP Toolbox for Databases
  MCP_TRINO_version: latest

  # Presidio Analyzer & Anonymizer
  PRESIDIO_ANALYZER_version: latest
  PRESIDIO_ANONYMIZER_version: latest

  #Whisper
  WHISPER_version: latest

  # No Language Left Behind (NLLB)
  NLLB_version: main

  #hive
  HIVE_version: 3.1.2
  #hive metastore
  HIVE_METASTORE_version: 3.1.2
  HIVE_METASTORE_version_suffix: postgresql-metastore-s3

  #apache range
  RANGER_version: 2.2.0
  RANGER_postgresql_version: 12

  #Open Policy Agent (OPA)
  OPA_version: 1.6.0-dev
  
  #Strya Enterprise OPA (Styra)
  STYRA_EOPA_version: 1.41.1-23-debug

  #Open Policy Agent (OPA)
  CEDAR_version: latest

  #Open Policy Administration Layer (OPAL)
  OPAL_version: 0.8.0
  
  #atlas
  ATLAS_version: 2.2.0

  #datahub
  DATAHUB_version: head
  DATAHUB_ACTIONS_version: head

  #datahub
  OPENMETADATA_version: 1.8.1

  #amunden
  AMUNDSEN_FRONTEND_version: 4.3.0
  AMUNDSEN_SEARCH_version: 4.2.0
  AMUNDSEN_METADATA_version: 3.13.0

  #Data Product Portal
  DATA_PRODUCT_PORTAL_version: 0.3.1

  #Marquez
  MARQUEZ_version: 0.51.1
  MARQUEZ_WEB_version: 0.51.1

  #CKAN
  CKAN_version: 2.10
  CKAN_DATAPUSHER_version: 0.0.21

  #Dataverse
  DATAVERSE_version: alpha

  #cassandra
  CASSANDRA_5_version: 5.0
  CASSANDRA_4_version: 4.1
  CASSANDRA_3_version: 3.11

  REAPER_version: latest

  # DataStax Enterprise (DSE)
  DATASTAX_version: 6.8.44
  DATASTAX_OPSCENTER_version: 6.8.36

  #elasticsearch
  ELASTICSEARCH_7_version: 7.17.28
  ELASTICSEARCH_8_version: 8.17.4

  # OpenSearch
  OPENSEARCH_version: 2
  OPENSEARCH_DASHBOARDS_version: 2

  # Various Elasticsearch / OpenSearch UIs
  DEJAVU_version: latest
  CEREBRO_version: latest
  ELASTICSEARCHHQ_version: latest
  ELASTICVUE_version: latest

  # Splunk
  SPLUNK_version: 9.1

  #hue
  HUE_version: 4.11.0
  HUE_POSTGRES_version: 10

  #streamsets
  STREAMSETS_version: 3.22.2
  STREAMSETS_TRANSFORMER_version: scala-2.12_3.19.0-latest
  STREAMSETS_EDGE_version: 3.13.0
  #streamsets dataops platform
  STREAMSETS_DATAOPS_version: 4.4.0

  #nifi
  NIFI_version: 1.28.1
  NIFI2_version: 2.4.0
  NIFI_REGISTRY_version: 1.28.1
  NIFI_REGISTRY2_version: 2.4.0
  NIFI_TOOLKIT_version: 1.28.1
  NIFI_TOOLKIT2_version: 2.4.0

  #Monitofi
  MONITOFI_version: latest

  #Apache StreamPipes
  STREAMPIPES_version: 0.69.0-SNAPSHOT

  #n8n
  N8N_version: 1.95.3

  #Cribl
  CRIBL_version: latest

  #Conduit
  CONDUIT_version: latest-nightly

  #FluentD
  FLUENTD_version: v1.16-debian

  #Fluent Bit
  FLUENT_BIT_version: 3.0

  #FluentD
  FILEBEAT_version: 8.11.3

  #nodered
  NODERED_version: 2.2.3

  # StreamSheets
  STREAMSHEETS_version: 2.5.3-milestone

  # Spring Cloud Data Flow
  SPRING_DATAFLOW_version: 2.9.3
  SPRING_SKIPPER_version: 2.8.3

  # Accenture Aspire
  ASPIRE_version: 5.2.1

  # Airbyte
  AIRBYTE_version: 0.40.33

  # Sqoop
  SQOOP_version: 1.4.7-hadoop3.2

  # Airflow
  AIRFLOW_2_version: 2.11.0
  AIRFLOW_3_version: 3.0.1

  # Mage AI
  MAGE_AI_version: 0.9.76

  # Kestra
  KESTRA_version: v0.22.13

  # Ofelia
  OFELIA_version: latest  

  # Zepelin
  ZEPPELIN_version: 0.11.2

  # Jupyter
  JUPYTER_MINIMAL_version: latest
  JUPYTER_R_version: latest
  JUPYTER_SCIPY_version: latest
  JUPYTER_TENSORFLOW_version: latest
  JUPYTER_DATASCIENCE_version: latest
  
  JUPYTER_SPARK_3_3_version: spark-3.3.2
  JUPYTER_SPARK_3_4_version: spark-3.4.1
  JUPYTER_SPARK_3_5_version: spark-3.5.3

  # JupyterHub
  JUPYTERHUB_version: main

  # Anaconda
  ANACONDA_version: '2024.10-1'

  # RStudio & Shiny Server
  RSTUDIO_version: 4
  SHINY_SERVER_version: 4

  # MLflow
  MLFLOW_SERVER_version: v2.22.1

  # Optuna
  OPTUNA_version: py3.7
  OPTUNA_DASHBOARD_version: 0.5.0

  # MindsDB
  MINDSDB_version: dev

  # Ollama
  OLLAMA_version: 0.9.0

  # LocalAI
  LOCAL_AI_version: v2.29.0
  
  # Open WebUI (prev. Ollama WebUI)
  OPEN_WEBUI_version: main

  # Alpaca WebUI
  ALPACA_WEBUI_version: latest

  # Anything LLM
  ANYTHING_LLM_version: latest

  # Anything LLM
  PERPLEXICA_version: main

  # big-AGI
  BIG_AGI_version: latest

  # AutGen Studio
  AUTOGEN_STUDIO_version: latest

  # CrewAI Studio
  CREWAI_STUDIO_version: latest

  # Agent Zero
  AGENT_ZERO_version: latest

  # LiteLLM 
  LITELLM_version: main-latest

  # Flowise 
  FLOWISE_version: 3.0.1

  # Langflow 
  LANGFLOW_version: 1.4.2

  # Langfuse 
  LANGFUSE_version: 2

  # OpenLIT
  OPENLIT_version: latest
  
  # Langwatch 
  LANGWATCH_version: latest

  # Langevals 
  LANGEVALS_version: latest

  # Langevals 
  ARIZE_PHOENIX_version: latest-nonroot

  # Opik 
  OPIK_version: latest

  # GPT Researcher
  GPT_RESEARCHER_version: latest

  # Local Deep Researcher
  LOCAL_DEEP_RESEARCHER_version: latest

  # Verba
  VERBA_version: latest

  # Verba
  RAGFLOW_version: dev

  # Verba
  NEO4j_KG_BUILDER_version: latest

  # dataiku data science studio
  DATAIKU_DSS_version: 13.4.1

  # drools KIE server
  KIE_SERVER_version: 7.61.0.Final

  # OpenTelemetry Collector
  OTEL_COLLECTOR_version: latest

  # Zipkin
  ZIPKIN_version: latest

  # Jaeger
  JAEGER_version: latest

  # Pitchfork
  PITCHFORK_version: latest

  #promtail
  PROMTAIL_version: main

  #loki
  LOKI_version: main

  #Tempo
  TEMPO_version: latest

  #grafana
  GRAFANA_version: 12.0.1
  #kibana
  KIBANA_7_version: 7.17.28  # should match elasticsearch version (minor increases should work though)
  KIBANA_8_version: 8.17.4    # should match elasticsearch version (minor increases should work though)

  # Metabase
  METABASE_version: latest
  # Apache Superset
  SUPERSET_version: latest-dev
  # Redash
  REDASH_version: preview

  # Smashing Dashboard
  SMASHING_version: 1.3.0

  # Tipboard Dashboard
  TIBOARD_version: 1.4.3

  # Chartboard Dashboard (fork of tipboard)
  CHARTBOARD_version: latest

  # ReTool 
  RETOOL_version: latest

  # ReTool 
  TOOLJET_version: latest

  # Streamlit 
  STREAMLIT_python_version: 3.9

  # Baserow
  BASEROW_version: latest  

  #Memcached
  MEMCACHED_version: 1.6

  #redis
  REDIS_version: 7.4
  REDIS_EXPORTER_version: latest
  REDIS_STACK_version: 7.2.0-v10
  REDIS_INSIGHT_version : latest
  REDIS_COMMANDER_version : latest

  #valkey
  VALKEY_version: 8.1

  #mongo
  MONGO_version: 8
  MONGO_EXPRESS_version: latest
  MONGO_ADMIN_version: latest

  #solr
  SOLR_version: 9.5

  #neo4j
  JANUSGRAPH_version: 1.0.0-20231010-065545.e3799d4

  #invana
  INVANA_ENGINE_version: latest
  INVANA_STUDIO_version: latest

  #neo4j
  NEO4J_5_version: 5.26
  NEO4J_4_version: 4.4

  #MCP Neo4j
  MCP_NEO4J_CYPHER_version: latest
  MCP_NEO4J_MEMORY_version: latest

  # Graphiti
  GRAPHITI_version: v0.12.0pre5

  #NeoDash
  NEODASH_version: latest

  #Quine
  QUINE_version: 1.5.1

  #Memgraph
  MEMGRAPH_version: 3.2.1
  MEMGRAPH_MAGE_version: 3.2.1
  # Deprecated
  MEMGRAPH_PLATFORM_version: 2.14.1-memgraph2.14.1-lab2.11.1-mage1.14.1

  #ArcadeDB
  ARCADEDB_version: 24.2.1

  #Dgraph
  DGRAPH_version: v24.1.3

  #stardog
  STARDOG_version: latest
  #stardog-studio
  STARDOG_STUDIO_version: current

  #graphdb
  GRAPHDB_FREE_version: 10.8.4
  GRAPHDB_version: 10.8.5

  # Jena Fuseki
  JENA_FUSEKI_version: 4.8.0

  # influxdb (1.8 is the latest OSS version, 1.9, 1.10 and 1.11 are only Entrprise)
  INFLUXDB_version: 1.8
  CHRONOGRAF_version: 1.10
  KAPACITOR_version: 1.7
  INFLUXDB_UI_version: latest

  TELEGRAF_version: 1.34

  INFLUXDB2_version: 2.7

  INFLUXDB3_version: 3-core
  INFLUXDB3_EXPLORER_version: latest

  # QuestDB
  QUESTDB_version: 7.4.0

  # Kudu
  KUDU_version: 1.17

  # Chroma
  CHROMA_version: 0.4.25.dev139
  
  # Qdrant
  QDRANT_version: v1.8.4

  # Weaviate
  WEAVIATE_version: 1.24.10

  # Milvus
  MILVUS_version: v2.5.12
  ATTU_version: v2.4

  # Infinity
  INFINITY_version: v0.5.0-dev2

  VECTOR_ADMIN_version: latest

  # DuckDB
  DUCKDB_version: v1.2.2

  # QuackFlight
  QUACKFLIGHT_version: 1.2.2

  # Druid
  DRUID_version: 29.0.1

  # Pinot
  PINOT_version: 1.1.0

  # Starrocks
  STARROCKS_version: 3.3-latest

  # Clickhouse
  CLICKHOUSE_version: 25.3
  CLICKHOUSE_UI_version: latest

  #prometheus
  PROMETHEUS_version: v2.51.2
  PROMETHEUS_PUSHGATEWAY_version: v1.8.0
  PROMETHEUS_NODEEXPORTER_version: v1.7.0
  PROMETHEUS_ALERTMANAGER_version: v0.27.0

  #tile38
  TILE38_version: 1.32.2

  # etcd
  ETCD_version: v3.5.10
  ETCD_BROWSER_version: latest

  # Yugabyte
  YUGABYTE_version: 2.14.16.0-b17

  #SingleStore
  SINGLE_STORE_version: 0.2.18

  #Oracle RDBMS 
  ORACLE_XE_version: 21
  ORACLE_FREE_version: 23.5.0.0
  ORACLE_OCI_FREE_version: 23
  ORACLE_ADB_FREE_version: 24.11.4.2-23ai
  ORACLE_EE_version: 18.9.0.0

  #Oracle SQLcl
  ORACLE_SQLCL_version: latest

  #Oracle Rest Data Service (ORDS) 
  ORACLE_REST_DATA_SERVICE_version: latest

  #mysql
  MYSQL_version: 8

  #mariadb
  MARIADB_version: 11

  #sqlserver
  SQLSERVER_version: 2019-latest

  #postgresql and different extensions
  POSTGRESQL_version: 17
  POSTGRESQL_POSTGIS_version: 17-master
  POSTGRESQL_PGVECTOR_version: pg17
  POSTGRESQL_PGVECTO_RS_version: pg17-v0.4.0
  POSTGRESQL_AGE_version: release_PG16_1.5.0
  POSTGRESQL_POSTGIS_WE_version: 17-3.5
  POSTGRESQL_PGDUCKDB_version: 17-v0.2.0

  #postgres
  POSTGREST_version: latest

  # pgAdmin
  PGADMIN_version: latest

  # supabase
  SUPABASE_STUDIO_version: 20250224-d10db0f
  SUPABASE_AUTH_version: v2.169.0
  SUPABASE_REST_version: v12.2.8
  SUPABASE_REALTIME_version: v2.34.31
  SUPABASE_STORAGE_version: v1.19.1
  SUPABASE_IMGPROXY: v3.8.0
  SUPABASE_META_version: v0.86.0
  SUPABASE_EDGE_RUNTIME_version: v1.67.2
  SUPABASE_ANALYTICS_version: 1.11.0
  SUPABASE_POSTGRESQL_version: 15.8.1.044
  SUPABASE_VECTOR_version: 0.28.1-alpine  
  SUPABASE_SUPAVISOR_version: 2.3.9   

  #timescaledb
  TIMESCALEDB_version: 2.14.2-pg16

  #adminer
  ADMINER_version: latest

  #adminer
  CLOUDBEAVER_version: latest

  #SQLPad
  SQLPAD_version: latest
  
  #SQLChat
  SQLCHAT_version: latest

  #Querybook
  QUERYBOOK_version: latest

  #DbGate
  DBGATE_version: latest  

  #NocoDB
  NOCODB_version: latest  

  # QUIX
  QUIX_version: latest

  #Hazelcast
  HAZELCAST_version: 5.4
  HAZELCAST_MC_version: latest

  # Apache Ignite
  IGNITE_version: 2.14.0
  GRIDGAIN_CC_version: 2021.08.00

  #axon
  AXON_version: 4.6.7

  #eventstore
  EVENTSTORE_version: 22.10.0-buster-slim

  #trino
  TRINO_version: 476
  STARBURSTDATA_version: 472-e
  TRINO_CLI_version: latest

  # Trino Gateway
  TRINO_GATEWAY_version: latest

  # Trino-LB (Load Balancer)
  TRINO_LB_version: 0.5.0

  #presto
  PRESTO_version: 0.286
  AHANA_version: 0.286
  PRESTO_CLI_version: latest

  #dremio
  DREMIO_version: 25.2

  #apache drill
  DRILL_version: 1.20.2

  #hasura
  HASURA_version: v2.38.1-ce

  #GraphQL Mesh
  GRAPHQL_MESH_version: latest-all

  #directus
  DIRECTUS_version: 9

  #Tyk API Gateway
  TYK_version: v5.7
  TYP_PUMP_version: v1.12

  #Kong API Gateway
  KONG_version: 3.10

  #Kong decK
  KONG_DECK_version: latest

  # Konga
  KONGA_version: latest

  # Kong Admin UI
  KONG_ADMIN_UI_version: 0.5.3

  # KongMap
  KONG_MAP_version: latest

  #Curity Identity Server
  CURITY_version: 7.6.0

  #Nuclio
  NUCLIO_version: stable-amd64

  #mosquitto
  MOSQUITTO_version: 2.0

  # hivemq
  HIVEMQ3_version: 3.4.7
  HIVEMQ4_version: 4.6.1

  # emq
  EMQX_oss_version: 4.3.11
  EMQX_enterprise_version: 4.4.0

  MQTTX_CLI_version: latest
  MQTTX_WEB_version: latest

  # mqtt ui
  HIVEMQ_MQTT_WEB_CLIENT_version: latest

  # cedalo
  CEDALO_MANAGEMENT_CENTER_version: 2.5.8

  # Thingsboard
  THINGSBOARD_version: 3.3.4.1

  #ActiveMQ
  ACTIVEMQ_CLASSIC_version: 5.18.2
  ACTIVEMQ_ARTEMIS_version: 2.30.0

  #RabbitMQ
  RABBITMQ_version: 3.9-management

  #NATS
  NATS_version: 2.10

  #Solace PubSub+
  SOLACE_version: 10.7

  #Solace Kafka Proxy
  SOLACE_KAFKA_PROXY_version: latest

  CAMUNDA_BPM_PLATFORM_version: 7.16.0
  CAMUNDA_OPTIMIZE_version: 3.6.5
  CAMUNDA_ZEEBE_version: 8.3.2
  CAMUNDA_OPERATE_version: 0.26.1
  CAMUNDA_ZEEQS_version: 1.0.0

  # Softproject X4 Server
  X4_SERVER_version: 7.3.4

  #IOEvent Cockpit
  IOEVENT_COCKPIT_version: 2.1.1

  #Pure FTPd
  PURE_FTPD_version: latest
  
  #sftp
  SFTP_version: latest

  #sftpgo
  SFTPGO_version: latest

  FILEZILLA_version: latest

  #MailDev
  MAILDEV_version: 2.1.0

  #Mailpit
  MAILPIT_version: v1.9

  #MailHog
  MAILHOG_version: v1.0.1

  # Penthao Webspoon
  PENTHAO_version: 0.9.0.22

  # Minio
  MINIO_version: RELEASE.2025-05-24T17-08-30Z

  ADMINIO_UI_version: latest
  ADMINIO_API_version: latest
  MINIO_WEB_version: v0.2.5

  MINIO_KES_version: 2025-01-30T09-41-53Z
  
  # Garage
  GARAGE_version: v1.1.0
  GARAGE_WEBUI_version: latest

  FILESTASH_version: latest
  S3MANAGER_version: latest
  AWSCLI_version: latest
  AZURECLI_version: latest
  AZURE_STORAGE_EXPLORER_version: latest

  ICEBERG_REST_CATALOG_version: 1.6.0

  # LakeFS
  LAKEFS_version: 1
  LAKEFS_HOOKS_version: latest

  # Project Nessie
  NESSIE_version: 0.100.0

  UNITY_CATALOG_version: v0.2.1
  UNITY_CATALOG_UI_version: 0.2.1-5d668c1

  # Code Server
  CODE_SERVER_version: latest

  # Taiga
  TAIGA_version: latest

  # Taskcafe
  TASKCAFE_version: latest

  # Focalboard
  FOCALBOARD_version: latest

  # Mock Server
  MOCK_SERVER_version: latest
  
  # DBT CLI (Data Build Tool)
  DBT_version: latest

  # Excalidraw
  EXCALIDRAW_enable: latest

  # DrawIO
  DRAWIO_version: latest

  # Code Server
  FIREFOX_version: latest  

  # File Browser
  FILE_BROWSER_version: latest

  # Vault
  VAULT_version: 1.18

  # Keycloak
  KEYCLOAK_version: 22.0

  # Authelia
  AUTHELIA_version: 4

  # Swagger API Management
  SWAGGER_EDITOR_version: latest
  SWAGGER_UI_version: latest

  # AsyncAPI Studio 
  ASYNCAPI_STUDIO_version: latest

  # Postman
  POSTMAN_version: latest

  # Pact Broker
  PACT_BROKER_version: 2.110.0-pactbroker2.107.1

  # Data Mesh Manager
  DATA_MESH_MANAGER_version: latest

  # Data Contract Manager
  DATA_CONTRACT_MANAGER_version: latest

  # Data Contract CLI
  DATA_CONTRACT_CLI_version: latest

  # Microcks 
  MICROCKS_version: latest

  # Portainer
  PORTAINER_version: alpine-sts
  # Docker Exec Web Console
  DOCKER_EXEC_WEBCONSOLE_version: latest
  # Rancher
  RANCHER_version: latest

  CETUSGUARD_version: v1
  NGROK_version: 3
  CADVISOR_version: v0.47.2
  GLANCES_version: latest-full
  DOCKER_REGISTRY_version: 2
  DOCKER_REGISTRY_UI_version: latest

  DOCKER_IN_DOCKER_version: 28-dind
  
  JENKINS_version: lts-jdk21

  GITWEB_version: latest

  HAWTIO_version: latest
  SPRING_BOOT_ADMIN_version: 3.4.1
  WETTY_version: latest

  RANETO_VIEWER_version: latest
  MARKDOWN_MADNESS_version: latest
  MARKDOWN_VIEWER_version: latest
  LOG4BRAINS_version: latest

  WATCHTOWER_version: 1.5.1

  #Python
  PYTHON_version: 3.8.1-alpine3.11

  #S3FS
  S3FS_version: 1.95

  # Web Protégé 
  WEB_PROTEGE_version: latest

  # Blaze FHIR
  HAPI_FHIR_version: v6.10.1

  # Blaze FHIR
  BLAZE_FHIR_version: 0.23  

  # LinxuForHealth (IBM) FHIR serer
  LFH_FHIR_version: 5.1.1

  # Miracum FHIR Gateway
  FHIR_GATEWAY_version: v3.12.8

templates:
  - src: templates/docker-compose.yml.j2
    dest: destination/docker-compose.yml
    include_vars :
      - vars/config.yml
      - /tmp/config.yml
